### ISSUE TITLE
Unable to get a response from chatbot

### ISSUE THREAD

**Issue by saisamarthtaluri** [freistli/rootbot#15]
I followed all the steps correctly and deployed the app. I made small changes to deploy.ps1 to use an existing resource group and not create a new one. After deploying everything, I try to test the bot on web chat but get this:

<img width="521" alt="image" src="https://github.com/freistli/rootbot/assets/95733415/cf1d96a7-db69-4c39-9d85-7612f54b7f2f">

I am not sure why this is happening since I specified the right version and model of gpt-35-turbo.

**Comment by freistli** [comment]
Hi @saisamarthtaluri , seems it is a GPT service side issue. Did the error still occur? Please make sure you are using the Model Deployment name (not the model name) from Azure OpenAI.

**Comment by saisamarthtaluri** [comment]
Hi @freistli, looks like I had the wrong deployment version. Your chat model must use version 0301 instead of 0613. Thanks for your response.
