### ISSUE TITLE
Express Deploy hangs during Azure function creation

### ISSUE THREAD

**Issue by EricTheSquirrel** [freistli/rootbot#17]
Running into an issue where the Express Deploy hangs with the following error AFTER creating the resource group. Sits in the while and never progresses:

Deploy and Build backend Azure Resource with AZChatGPTFuncAppDeploy.bicep, will take several minutes

**Comment by freistli** [comment]
Hi @EricTheSquirrel , the Azure function deploy part will take a while without progress bar. Please ensure waiting 10 minutes or so and then check the result. You can delete the resource group and run the script again to see the result.
